### ISSUE TITLE
An item with the same key has already been added. Key: PolicyHttpMessageHandler.PriorResponse

### ISSUE THREAD

**Issue by kdcllc** [kdcllc/Bet.Extensions.Shopify#5]
Prior to `6.0.0-rc.2.21459.18` version of `DotNetCore`, the following policy registration worked but now it is causing an exception:

https://github.com/kdcllc/Bet.Extensions.Shopify/blob/9a112fe0cc597bad78af3583ec1cb9c583f95d7a/src/Bet.Extensions.Shopify/DependencyInjection/ShopifyServiceExtensions.cs#L47-L68

[PolicyHttpMessageHandler](https://github.com/dotnet/aspnetcore/blob/8d5212dbb252e25647d98309fd5c583a23732860/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs)

```
System.ArgumentException: An item with the same key has already been added. Key: PolicyHttpMessageHandler.PriorResponse
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Net.Http.HttpRequestOptions.System.Collections.Generic.IDictionary<System.String,System.Object>.Add(String key, Object value)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

**Comment by kdcllc** [comment]
@TiraelSedai I am glad it was helpful to you. I know it took me a bit of time to figure out what was going on.
